[project]
name = "tinyagent"
version = "0.1.0"
description = "Minimal Python CLI agent"
requires-python = ">=3.12"
dependencies = [
    "click",
    "rich",
    "python-dotenv",
    "anthropic",
    "terminal-bench>=0.2.17",
]

[project.scripts]
tinyagent = "tinyagent.__main__:cli"
